spring.application.name=AquaTresor
server.port=8090

# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/AquaTresor
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JPA / Hibernate configurations
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Logging
logging.level.org.springframework=DEBUG
logging.level.org.springframework.security=DEBUG

spring.main.allow-circular-references=true
